[cases.bench_superblocks_found]
# support benchmarking with files
defines.N = [0, 1024]
defines.FILE_SIZE = 8
defines.CHUNK_SIZE = 8
code = '''
    dbc_lfs_t lfs;
    dbc_lfs_format(&lfs, cfg) => 0;

    // create files?
    dbc_lfs_mount(&lfs, cfg) => 0;
    char name[256];
    uint8_t buffer[CHUNK_SIZE];
    for (dbc_lfs_size_t i = 0; i < N; i++) {
        sprintf(name, "file%08x", i);
        dbc_lfs_file_t file;
        dbc_lfs_file_open(&lfs, &file, name,
                DBC_LFS_O_WRONLY | DBC_LFS_O_CREAT | DBC_LFS_O_EXCL) => 0;

        for (dbc_lfs_size_t j = 0; j < FILE_SIZE; j += CHUNK_SIZE) {
            for (dbc_lfs_size_t k = 0; k < CHUNK_SIZE; k++) {
                buffer[k] = i+j+k;
            }
            dbc_lfs_file_write(&lfs, &file, buffer, CHUNK_SIZE) => CHUNK_SIZE;
        }

        dbc_lfs_file_close(&lfs, &file) => 0;
    }
    dbc_lfs_unmount(&lfs) => 0;

    BENCH_START();
    dbc_lfs_mount(&lfs, cfg) => 0;
    BENCH_STOP();

    dbc_lfs_unmount(&lfs) => 0;
'''

[cases.bench_superblocks_missing]
code = '''
    dbc_lfs_t lfs;

    BENCH_START();
    int err = dbc_lfs_mount(&lfs, cfg);
    assert(err != 0);
    BENCH_STOP();
'''

[cases.bench_superblocks_format]
code = '''
    dbc_lfs_t lfs;

    BENCH_START();
    dbc_lfs_format(&lfs, cfg) => 0;
    BENCH_STOP();
'''

